pool:
  vmImage: 'windows-latest'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/*.html'
    codeCoverageToolOption: 'Cobertura'
    codeCoverageClassFilesDirectories: 'app/build/classes/java/main,list/build/classes/java/main,utilities/build/classes/java/main'
    codeCoverageFailIfEmpty: true
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
