/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multimodule.app;

import multimodule.list.LinkedList;

import static multimodule.utilities.StringUtils.join;
import static multimodule.utilities.StringUtils.split;
import static multimodule.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
